# Generated by Django 4.2.4 on 2023-08-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTS", "0002_pub_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pub",
            name="members",
        ),
        migrations.AddField(
            model_name="pub",
            name="max_members",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="pub",
            name="password",
            field=models.CharField(
                default=models.CharField(max_length=64), max_length=64
            ),
        ),
    ]
