# Generated by Django 4.2.4 on 2023-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTS", "0007_pub_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("name", models.CharField(max_length=256)),
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("name", models.CharField(max_length=256)),
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("preview_url", models.CharField(max_length=256)),
                (
                    "artists",
                    models.ManyToManyField(
                        blank=True, related_name="songs", to="GTS.artist"
                    ),
                ),
            ],
        ),
    ]
