# Generated by Django 4.2.4 on 2023-08-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTS", "0009_pub_track_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="album_cover",
            field=models.CharField(default="", max_length=256),
        ),
    ]
