# Generated by Django 4.2.4 on 2023-08-21 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("GTS", "0011_track_display_name_track_fastest_guess_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="fastest_guesser",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
