# Generated by Django 4.2.4 on 2023-08-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTS", "0012_alter_track_fastest_guesser"),
    ]

    operations = [
        migrations.AddField(
            model_name="pub",
            name="rounds",
            field=models.IntegerField(default=10),
        ),
    ]
